apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: namespaxe/hello-app:1.0
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "20Mi"
              cpu: "20m"